# Site settings
title: My Portfolio
author:
  name: Prodip Sarkar
  email: prodip1023@gmail.com
description: "I am a Full Stack Data Science Enginner"

# Build settings
remote_theme: jekyll/minima

#twitter_username: prodip9614327299
#github_username: prodip1989
#medium_username: prodip1023
#linkedin_username: prodip1023
#kaggle_username: prodip1023
